name: Build Windows Installer (MSI)

on:
  workflow_dispatch:

jobs:
  build-msi:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install WiX Toolset (for MSI)
        run: choco install wixtoolset -y

      - name: Build JAR (Maven)
        run: mvn -B clean package

      - name: Build MSI with jpackage
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist | Out-Null

          # Find the built jar automatically (first jar in target/)
          $jar = Get-ChildItem -Path target -Filter *.jar | Select-Object -First 1
          if (-not $jar) { throw "No JAR found in target/. Build failed." }

          jpackage `
            --type msi `
            --name RegexXmlCleaner `
            --app-version 1.0.0 `
            --vendor "Sanjay Tools" `
            --input target `
            --main-jar $jar.Name `
            --main-class com.sanjay.tools.RegexXmlCleanerApp `
            --dest dist `
            --win-menu `
            --win-shortcut `
            --win-dir-chooser

      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: RegexXmlCleaner-MSI
          path: dist/*.msi